global:
  tlsDisable: false

injector:
  image:
    repository: "hashicorp/vault-k8s"
    tag: "0.4.0"
  agentImage:
    repository: "vault"
    tag: "1.5.0"
   
server:
  image:
    repository: "vault"
    tag: "1.5.0"

  extraVolumes:
  - type: secret
    name: tls-test-server
  - type: secret
    name: kms-creds

  extraEnvironmentVars:
    VAULT_CACERT: "/vault/userconfig/tls-test-server/ca.crt"
    GOOGLE_REGION: "global"
    GOOGLE_PROJECT: "vault-helm-dev-246514"
    GOOGLE_APPLICATION_CREDENTIALS: "/vault/userconfig/kms-creds/credentials.json"

  ha:
    enabled: true
    raft:
      enabled: true
      config: |
        listener "tcp" {
          address = "[::]:8200"
          cluster_address = "[::]:8201"
          tls_cert_file = "/vault/userconfig/tls-test-server/server.crt"
          tls_key_file = "/vault/userconfig/tls-test-server/server.key"
        }

        storage "raft" {
          path = "/vault/data"
        }

        service_registration "kubernetes" {}

        seal "gcpckms" {
          project     = "vault-helm-dev-246514"
          region      = "global"
          key_ring    = "vault-helm-unseal-kr"
          crypto_key  = "vault-helm-unseal-key"
        }
